const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "+923423793553",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRU9uUk5VMGh0ZDNGZTI4SlYwckwybmtEbmJiNXJzaFc5ZytKT3doZm1VOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiczRUUHlSbFNrazdnL2txZFRiMFdnQkQxTnR6b0wzMk1WbjU1TkUrcGxWbz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJNQkE5eXhwZHI0anBpU09KQkZZdmxJRk0xTzFLWU5TcFFvUXRGTU5XMWxjPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiIxeE9Md2Vkb093dFpyV1htWFFuajNKRFIzdHB2OUd5SldrOTNxZDdrLzNJPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Im1NY3dHQkJ6SWdLUlJvRW5NWVhrTForeXBVWHNuNUg2b0UyNit4WElybnc9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNnRmpMdk83KzlzUHdJZlRGUFJMWFZKd2hMTk5DUEtWSnp4amJtMEZhQnc9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiU0ZzNTdrcnZzbFVidWJLS0h2Yzc3aVM0b29XRFptSk5jeU5tNTM2Nk0zOD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoieDVKMVNNZWV4V2JDVHo2UC9lV3FFQzFBd2tSd3hkNmh2N0NXYS84T1ZrTT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InU5UHRaY1JlWGFQS3FzZWxtUnJxWnhaaEZPYlBwSXFMeUpSOU5EU3hhU1BHOTBYMlZFOFJ1TkxMdWoxL2xqV1c1aFVOaUorVWI3VDhCVitibDdsT0F3PT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjksImFkdlNlY3JldEtleSI6ImZQNitSYVhibEdVelRNczhOTmxPaGJYVTNaMW1nRVhNNUVLWEs5bEhjeWM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiOTIzNDIzNzkzNTUzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjVDNzdCRTJBQTg0OTU4NDFCQTk1QjdCNUNBRjgwQzI4In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MzU5OTE4NDB9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IjlRa2psdGdpUWI2aEZVU05tSFhPdkEiLCJwaG9uZUlkIjoiMzg5Njg4ODQtM2I2YS00YjUyLWJiZmEtZjY2ZDgwMzA0NzY2IiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjFoS1BBaGY5MnBURDAvSXFZNm55UlZBUVkxbz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJvZ2tIck0xc3JNOFlsN2x0RWZtb2FzZTVnL009In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiMzdURUVaN0QiLCJtZSI6eyJpZCI6IjkyMzQyMzc5MzU1Mzo1MkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiLwn5KrIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKYTgxSkFERUlURTVMc0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJMZkE1aGdwQUx1V2MxZ0F6ZFhBTFFId3BRejRoeDM0c28yR3FLay9ySmxZPSIsImFjY291bnRTaWduYXR1cmUiOiJnRW5pcUVHTk9MK1hIanE5MVI3ckpFREcrWWxnclBVM0tpZENkbE5lSmhyZmVjeS9hV09ZUlNNZWI4ZFFyZXU4WTk2U0Jnc0NLQURGZ01HVVlyc0VEdz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiYzl1cWlmdXhsTm9UekxLZkgyMnFQcXVlUHlpc1ZpVUxhRk1ZK3NrbnplNUM1SVBVcmp0MnRvdzNxN2VVSW9vUi9LN2JFaFhJT0J1MEFLREtmTFFTQmc9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5MjM0MjM3OTM1NTM6NTJAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCUzN3T1lZS1FDN2xuTllBTTNWd0MwQjhLVU0rSWNkK0xLTmhxaXBQNnlaVyJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTczNTk5MTgyNSwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFNaDcifQ==",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
